### ISSUE TITLE
Request for contacting the creator of Crumby

### ISSUE THREAD

**Issue by DonaldTsang** [sin3hz/Mbooru#3]
There used to be an app called Crumby which has been moved away from Google Play (although it is safe and can be downloaded from its website), and if would be appreciated if you and him can collaborate on a "universal browser". 
The address of the developer  is http://getcrumby.com

**Comment by sin3hz** [comment]
It's hard to make an "universal browser".

**Comment by DonaldTsang** [comment]
The man who created Crumby did it for many imageboards, tumble, deviantart,  Imgur, Inkbunny and FurAffinity. See for yourself.

**Comment by Dovaa** [comment]
But this is something that the developer of that application should have decided, although we don't lose anything for proposing it to him :/

**Comment by sin3hz** [comment]
Crumby is hard to use. I prefer to use individual app.

**Comment by DonaldTsang** [comment]
The creator is creating a new update in the near future, so I think you and him can communicate on how to make the interface easier to use. That is what I hope. (Since Crumby uses a system similar to Overchan, where web address are saved in the bar by layers, and its main purpose is to collect pictures, expectation will be different)
